services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__DATABASE}
      POSTGRES_USER: ${APP_CONFIG__DB__USERNAME}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - "${APP_CONFIG__DB__PORT}:${APP_CONFIG__DB__PORT}"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"